ANL/Battery version 1.0
idaholab/HYBRID pull request #19
Opened 2021-07-27 18:01 UTC by wanghy-anl

Hello Konor,
I have added a package of Lithium-ion batteries in NHES.Systems.EnergyStorage.LithiumIonBattery. It contains three levels of battery models as well as the simulators.
I also included three sets of "gold" folders and the test scripts as depicted in "https://github.com/idaholab/HYBRID/wiki/Developing-Regression-Tests", namely "Test_LithiumIonBattery_Level_0", "Test_LithiumIonBattery_Level_1" and "Test_LithiumIonBattery_Level_2".

Let me know whether it can pass your test. First time doing so.

Thanks,
Haoyu

2021-09-13 20:30 UTC, klfrick2 requested changes
Comments in the files. In general it looks good, main things to address is making sure all the proper files are in the PR and that the battery models are able to express the power input; max storage capacity; max storage rate as W and W-hr's.

2021-09-13 20:30 UTC, klfrick2 commented on Models/NHES/Fluid/ClosureModels/HeatTransfer/package.order
> -Nu_DittusBoelter_Heat_Cool
This shouldn't automatically add a space.

2021-09-13 20:30 UTC, klfrick2 commented on Models/NHES/Systems/EnergyStorage/LithiumIonBattery/BatteryModels.mo
> +
We would like to have a variable that describes the Energy storage in the unit that is in units of W-hr. This is normally used in the energy storage fields.

2021-09-13 20:30 UTC, klfrick2 commented on Models/NHES/Systems/EnergyStorage/LithiumIonBattery/BatteryModels.mo
> +
We would like to have a variable that describes the Energy storage in the unit that is in units of W-hr. This is normally used in the energy storage fields.

2021-09-13 20:30 UTC, klfrick2 commented on Models/NHES/Systems/EnergyStorage/LithiumIonBattery/BatteryModels.mo
> +
In the inputs to the models can we put in the total storage size of the unit? E.g. Max Charge is 400MW-hr. Max input rate is 100MWe.

2021-09-13 20:30 UTC, klfrick2 commented on Models/NHES/Systems/EnergyStorage/LithiumIonBattery/Data/Data_TEDS.mo
> +
I don't think we need this file in the system for the Lithium Ion Battery.

2021-09-13 20:30 UTC, klfrick2 commented on Models/NHES/Systems/BalanceOfPlant/Turbine/CS_OTSG_TCV_Pressure_TBV_Power_Control.mo
> -within NHES.Systems.BalanceOfPlant.Turbine;
This file shouldn't be deleted.

2021-09-15 02:59 UTC, wanghy-anl commented on Models/NHES/Fluid/ClosureModels/HeatTransfer/package.order
> -Nu_DittusBoelter_Heat_Cool
Let's use your corrections. It's weird that I didn't touch this file at all. Maybe this file is altered by the Dymola software?

2021-09-15 03:00 UTC, wanghy-anl commented on Models/NHES/Systems/BalanceOfPlant/Turbine/CS_OTSG_TCV_Pressure_TBV_Power_Control.mo
> -within NHES.Systems.BalanceOfPlant.Turbine;
Let's use your corrections. It's weird that I didn't touch this file at all. Maybe this file is altered by the Dymola software?

2021-09-15 03:36 UTC, wanghy-anl commented on Models/NHES/Systems/EnergyStorage/LithiumIonBattery/BatteryModels.mo
> +
No problem. I added two parameters "TotalCapacity" and "InitialEnergyStored", which is in units of W-hr.

2021-09-15 03:37 UTC, wanghy-anl commented on Models/NHES/Systems/EnergyStorage/LithiumIonBattery/BatteryModels.mo
> +
No problem. I added the variable "ResidualEnergy", which is in units of W-hr.

2021-09-15 03:38 UTC, wanghy-anl commented on Models/NHES/Systems/EnergyStorage/LithiumIonBattery/BatteryModels.mo
> +
No problem. I added three parameters, "TotalCapacity" in W-hr, "MaxChargeRate" in W, and "MaxDischargeRate" in W.

2021-09-15 03:40 UTC, wanghy-anl commented on Models/NHES/Systems/EnergyStorage/LithiumIonBattery/Data/Data_TEDS.mo
> +
To be honest, I don't know the purpose of this data, either... But I will defer to you regarding whether this line should be deleted. I won't do any changes in this file in the latest push.

2021-09-16 15:33 UTC, klfrick2 approved these changes
These look good.

2021-09-16 15:33 UTC, merged